import Header from '@/Essentials/Header'
import './globals.css'
import { Sora } from 'next/font/google'
import Providers from '@/Component/Provider'
import Footer from '@/Essentials/Footer'
const inter = Sora({ subsets: ['latin'] })

export const metadata = {
  title: 'Hackathon Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers><Header/>
      <main className='px-20 pt-10 '>{children}<Footer/></main></Providers></body>
    </html>
  )
}
